### ISSUE TITLE
License info

### ISSUE THREAD

**Issue by psolymos** [noxify/gridsome-starter-skeleventy#1]
Hi @noxify - this Gridsome template is really nice and I am thinking about using it for one of my projects and I was wondering what is the license that applies to the template?

**Comment by noxify** [comment]
Hi @psolymos 
Thanks for the reminder about the license.

All my repositories are licensed under MIT.
I have checked the original theme repo, but there is no license - I think MIT is the best option for this.

I will update the repo tomorrow with the license info.



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
